//! Tunable constants for TessariDB.
//!
//! Every magic number in the workspace lives here, named, typed, and documented
//! with its unit and the reasoning behind its value. Business and engine code
//! never carries a bare numeric literal.

#![forbid(unsafe_code)]
// `expect_used` and `as_conversions` govern production code; a test states its own expectations.
#![cfg_attr(test, allow(clippy::expect_used, clippy::as_conversions))]

mod access;
mod cluster;
mod language;
mod network;
mod search;
mod spatial;
mod storage;

pub use access::{
    FREE_SIGN_IN_FAILURES, MAX_SESSION_TOKENS, MAX_SIGN_IN_VERIFICATIONS, PASSWORD_HASH_LANES,
    PASSWORD_HASH_MEMORY_KIB, PASSWORD_HASH_PASSES, SESSION_TOKEN_SECONDS,
    SIGN_IN_BACKOFF_CEILING_MILLIS, SIGN_IN_BACKOFF_MILLIS, UNSEAL_SECONDS,
};
pub use cluster::{
    ACROSS_LAPSE_ROUNDS, AWARENESS_SECONDS, BALANCE_SECONDS, CAMPAIGN_MILLIS,
    COLLECTION_BUDGET_BYTES, COLLECTION_PAGE_RECORDS, COLLECTION_RECORDS, COLLECTION_SECONDS,
    COORDINATED_SECONDS, ELECTION_JITTER_MILLIS, GATHER_FOLD_RECORDS, GATHER_PAGE_BYTES,
    GATHER_PAGE_RECORDS, GATHER_RECORDS, GREETING_SECONDS, PREFERENCE_YIELD_SECONDS,
    REPLICA_COPY_GRACE_SECONDS, ROUND_MILLIS, SIGN_IN_ASK_MILLIS, STALENESS_FLOOR_SECONDS,
    STREAM_HEARTBEAT_MILLIS, STREAM_LOGS_MAX,
};
pub use language::{EVENT_DEPTH_LIMIT, MAX_VIEW_DEPTH};
pub use network::{
    ACROSS_DOOR_IDLE_SECONDS, ACROSS_KEPT_IDLE_SECONDS, ACROSS_KEPT_PER_PEER, FRAME_STALL_SECONDS,
    HTTP_MAX_BODY_BYTES, MAX_CONNECTIONS, MAX_STORE_CALLS, PEER_CONNECTIONS,
    SOCKET_MAX_FRAME_BYTES, SOCKET_MAX_MESSAGE_BYTES, WIRE_SOCKET_MAX_MESSAGE_BYTES,
};
pub use search::{
    BM25_B, BM25_K1, FUSION_DEPTH, FUSION_K, ORDERED_FILTER_REACH, SEARCH_FUZZY_EXAMINATION_CAP,
    SEARCH_FUZZY_EXPANSION_CAP, SEARCH_FUZZY_MAX_EDITS, SEARCH_FUZZY_PREFIX,
    SEARCH_PREFIX_EXPANSION_CAP, SEARCH_PREFIX_MINIMUM, SEARCH_PREFIX_SCORE_EXAMINATION_CAP,
    SEARCH_SNIPPET_TOKENS,
};
pub use spatial::{
    SPATIAL_INDEX_CELLS_PER_RECORD, SPATIAL_NEAREST_EXAMINATION_CAP, SPATIAL_QUERY_CELLS,
    SPATIAL_WALK_SUBTREE_ENTRIES,
};
pub use storage::{
    COMMIT_BACKOFF_CEILING, COMMIT_BACKOFF_STEP, DEFAULT_LOG_RETENTION_RECORDS, HISTORY_EVENTS,
    HISTORY_SCAN_RECORDS, KAFKA_QUARANTINE_HELD, MAX_CLAIM_RECORDS, MAX_COMMIT_ATTEMPTS,
    MAX_GROUP_BYTES, MAX_GROUP_COMMITS, ORDERED_SCAN_BATCH_ENTRIES, PLANNER_SCAN_FLOOR_RECORDS,
    RANGE_SCAN_BATCH_ENTRIES, SKIP_BATCH_RECORDS, STATISTICS_BUCKETS, STATISTICS_COMMON_VALUES,
    STATISTICS_PER_PASS, STATISTICS_STALE_FLOOR_CHANGES,
};
