[package]
name = "tessari-types"
description = "Shared value types, record identifiers and newtypes for TessariDB"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
rust_decimal.workspace = true

[dev-dependencies]
rust_decimal.workspace = true

[lints]
workspace = true
