[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
license = "LicenseRef-bgv-db-Commercial"
authors = ["boogvar"]
repository = "https://github.com/BoogVAr/bgv-db"
publish = false

[workspace.dependencies]
bgv-db-types = { path = "crates/bgv-db-types" }
bgv-db-constants = { path = "crates/bgv-db-constants" }
bgv-db-kv = { path = "crates/bgv-db-kv" }
bgv-db-encoding = { path = "crates/bgv-db-encoding" }
bgv-db-storage = { path = "crates/bgv-db-storage" }

thiserror = "2"
serde = { version = "1", features = ["derive"] }

proptest = "1"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
missing_docs = "warn"

[workspace.lints.clippy]
cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_sign_loss = "deny"
cast_precision_loss = "deny"
unwrap_used = "deny"
panic = "deny"
arithmetic_side_effects = "warn"
todo = "warn"
unimplemented = "warn"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
debug = "line-tables-only"
opt-level = 0

[profile.dev.package."*"]
opt-level = 2

[profile.dev.build-override]
opt-level = 3
