[package]
name = "bgv-db-ql"
description = "bgvQL: lexer, parser and abstract syntax for bgv-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
bgv-db-types.workspace = true
rust_decimal.workspace = true
thiserror.workspace = true

[lints]
workspace = true
